name: workflow_dispatch

on:
  workflow_dispatch:
    inputs:
      param:
        description: ""
        required: true
        default: "[]"

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo ${{ github.event.inputs.param }}
